
#' Check that participants were closed correctly.
#' 
#' This function checks that participants were closed correctly (currently,
#' just that those who are closed as triple-negatives actually were).
#' 
#' @return
#' This function returns a data.frame of participants whose records aren't
#' consistent with their closing reason. The data.frame includes
#' study ID, participant status, visit date, and test result indicators.
#' 
#' @param cleanlist The list of cleaned TO1 data generated by 
#'   \code{\link{clean_to1}}
#' 
#' @seealso \code{\link{to_close}} for participants who should be closed.
#' 
#' @export


closed_check <- function(cleanlist) {

    # Get study IDs and status
    parts <- cleanlist$master[ , c("StudyId", "CloseReason", "VisitDate")]



    ########################################################################### 
    # Identify the triple-negatives
    ########################################################################### 

    # Participants can have multiple tests, so I'll need to expand this
    # to accommodate that...
    parts$tst_neg <- parts$StudyId %in% 
        cleanlist$skintest$StudyId[cleanlist$skintest$result %in% "Negative"]

    parts$qft_neg <- parts$StudyId %in% 
        cleanlist$qft$StudyId[cleanlist$qft$result %in% 
                              c("Negative", "Indeterminate")]

    parts$tspot_neg <- parts$StudyId %in% 
        cleanlist$tspot$StudyId[cleanlist$tspot$result %in% 
                                c("Negative", "Borderline", "Invalid")]

    parts$trip_neg <- with(parts, tst_neg & qft_neg & tspot_neg)


    # Identify those who were closed as triple-negative but weren't
    parts$not_trip_neg <- with(parts, 
                               CloseReason %in% 'Triple Negative' &
                               trip_neg %in% FALSE)

    ########################################################################### 
    # Identify individuals with missing results
    ########################################################################### 

    parts$tst_missing <- parts$StudyId %in% 
        cleanlist$skintest$StudyId[is.na(cleanlist$skintest$result)]

    parts$qft_missing <- parts$StudyId %in% 
        cleanlist$qft$StudyId[is.na(cleanlist$qft$result)]

    parts$tspot_missing <- parts$StudyId %in% 
        cleanlist$tspot$StudyId[cleanlist$tspot$result %in% 
                                c(NA, "Test Not Performed")]

    parts$any_missing <- with(parts, tst_missing | qft_missing | tspot_missing)


    # Identify those who were closed without all results in
    parts$missing_results <- with(parts, 
                                  CloseReason %in% 'Triple Negative' &
                                  any_missing %in% TRUE)



    ########################################################################### 
    # Provide a nicely-labeled indicator of reason for incorrect closing
    ########################################################################### 

    parts$close_problem <- NA

    parts$close_problem[parts$not_trip_neg] <- "Not Triple-Negative"

    parts$close_problem[parts$missing_results] <- "Missing Test Result"


    ########################################################################### 
    # Return any participants closed for the incorrect reason
    ########################################################################### 

    parts[!is.na(parts$close_problem), 
          c("StudyId", "VisitDate", "CloseReason", "close_problem")]


}
