

#' Check that triple-negative individuals are closed to follow-up.
#' 
#' This function checks that individuals who had negative TST, QFT, and TSPOT
#' were closed.
#' 
#' @return
#' This function returns a data.frame of participants who are negative
#' on all three tests but have not yet been closed. The data.frame includes
#' study ID, participant status, visit date, and test result indicators.
#' 
#' @param cleanlist The list of cleaned TO1 data generated by 
#'   \code{\link{clean_to1}}
#' 
#' @seealso \code{\link{closed_check}} for participants who were closed
#'   incorrectly.
#' 
#' @export


to_close <- function(cleanlist) {

    # Get study IDs and status
    parts <- cleanlist$master[ , c("StudyId", "CloseReason", "EnrollDate")]



    ########################################################################### 
    # Identify the triple-negatives
    ########################################################################### 

    # Participants can have multiple tests, so I'll need to expand this
    # to accommodate that...
    parts$tst_neg <- parts$StudyId %in% 
        cleanlist$skintest$StudyId[cleanlist$skintest$result %in% "Negative"]

    parts$qft_neg <- parts$StudyId %in% 
        cleanlist$qft$StudyId[cleanlist$qft$result %in% 
                              c("Negative", "Indeterminate")]

    parts$tspot_neg <- parts$StudyId %in% 
        cleanlist$tspot$StudyId[cleanlist$tspot$result %in% 
                                c("Negative", "Borderline", "Invalid")]

    parts$trip_neg <- with(parts, tst_neg & qft_neg & tspot_neg)



    ########################################################################### 
    # Return any triple-negative participants who aren't closed
    ########################################################################### 

    parts[parts$trip_neg %in% TRUE & parts$CloseReason %in% "Open", ]


}
